### ISSUE TITLE
Ошибка сервера при поиске составного слова по чтению `恐`

### ISSUE THREAD

**Issue by 0x009922** [olesya-wo/yarxi-site#1]
### Описание

_Название тикета говорит само за себя_

### Как вопроизвести

1. Перейти на вкладку "Составные слова"
2. В поле "Чтение" ввести `恐`
3. Нажать "Найти"
4. Выдаётся огромная всплывашка с ошибкой от сервера

### Ожидаемое поведение

Ожидал, что если вводные данные и некорректные, ошибка будет говорить именно об этом, а не о кишках сервера.

### Скриншоты

<img width="257" alt="Pasted image 20231021125650" src="https://github.com/olesya-wo/yarxi-site/assets/43530070/4b58210f-8599-46e1-80e5-c8cc60fd60ce">

**Comment by olesya-wo** [comment]
Не могу воспроизвести
![image](https://github.com/olesya-wo/yarxi-site/assets/29059032/1fb85992-acd1-4fa7-89d8-34e06bdd6a47)

**Comment by 0x009922** [comment]
Хм, и я сейчас не могу. Стоило проверить, прежде чем заводить тикет.
