### ISSUE TITLE
Кнопки управление кол-вом штрихов не имеют подсказок

### ISSUE THREAD

**Issue by 0x009922** [olesya-wo/yarxi-site#2]
### Описание

<img width="811" alt="image" src="https://github.com/olesya-wo/yarxi-site/assets/43530070/a02878d7-0905-44c9-966c-d2c2edca7cdd">

Эти кнопки не имеют всплывашек, т.е. при наведении не показывается, что они делают

**Comment by olesya-wo** [comment]
Спасибо, исправлено
