### ISSUE TITLE
[словарь] Странный рендер в слове 「区民」

### ISSUE THREAD

**Issue by 0x009922** [olesya-wo/yarxi-site#4]
Закрывающая круглая скобка почему-то в _италике_:

<img width="569" alt="image" src="https://github.com/olesya-wo/yarxi-site/assets/43530070/d3bf70ac-91b2-448d-8a7c-1f24bb6c72d9">

**Comment by olesya-wo** [comment]
Исправлено в новой версии
![image](https://github.com/olesya-wo/yarxi-site/assets/29059032/2eed6f67-d756-4d90-ad19-b6ead26662a6)
