### ISSUE TITLE
[feature request] Поиск радикала по кодовому слову

### ISSUE THREAD

**Issue by 0x009922** [olesya-wo/yarxi-site#5]
**Связан ли ваш запрос с какой-то проблемой? Опишите это.**

Долго ищу в таблице радикал, кодовое слово которого я помню

**Опишите желаемое решение**

Иметь поисковый инпут в таблице радикалов, в который можно печатать кодовое слово, и по мере печатания подсвечивались бы релевантные ячейки по fuzzy-поиску

**Есть ли альтернативные решения?**

Сделать альтернативное отображение таблицы радикалов, но в виде списка, где по отсортировать радикалы по алфавиту кодового слова

**Дополнительный контекст**

Правда, не все радикалы имеют такие кодовые слова, но многие имеют.

**Comment by olesya-wo** [comment]
Реализовано в виде отдельной вкладки
![image](https://github.com/olesya-wo/yarxi-site/assets/29059032/823aa5c7-9a86-4e24-94de-50c29fc250d1)
